Create subcommands to jail command.

diff --git a/usr/bin/jail b/usr/bin/jail
--- a/usr/bin/jail
+++ b/usr/bin/jail
@@ -1,31 +1,46 @@
 #! /usr/bin/env bash
 
-jail_name="default"
-gnu_coreutils_commands="chcon chgrp chown chmod cp dd df dir dircolors install
-                        ln ls mkdir mkfifo mknod mktemp mv realpath rm rmdir
-			shred sync touch truncate vdir base64 cat cksum comm
-			csplit cut expand fmt fold head join md5sum nl numfmt
-			od paste ptx pr sha1sum sha224sum sha256sum sha384sum
-			sha512sum shuf sort split sum tac tail tr tsort
-			unexpand uniq wc arch basename chroot date dirname du
-			echo env expr factor false groups hostid id link
-			logname nice nohup nproc pathchk pinky printenv printf
-			pwd readlink runcon seq sleep stat stdbuf stty tee test
-			timeout true tty uname unlink uptime users who whoami
-			yes"
-copy_commands="bash $gnu_coreutils_commands"
-build_script="/dev/null"
+build() {
+	jail_name="default"
+	gnu_coreutils_commands="
+                chcon chgrp chown chmod cp dd df dir dircolors install ln ls
+                mkdir mkfifo mknod mktemp mv realpath rm rmdir shred sync touch
+                truncate vdir base64 cat cksum comm csplit cut expand fmt fold
+                head join md5sum nl numfmt od paste ptx pr sha1sum sha224sum
+                sha256sum sha384sum sha512sum shuf sort split sum tac tail tr
+                tsort unexpand uniq wc arch basename chroot date dirname du
+                echo env expr factor false groups hostid id link logname nice
+                nohup nproc pathchk pinky printenv printf pwd readlink runcon
+                seq sleep stat stdbuf stty tee test timeout true tty uname
+                unlink uptime users who whoami yes"
+	copy_commands="bash $gnu_coreutils_commands"
+	build_script="/dev/null"
+	REBUILD=false
 
-[ -f "$1" ] && while read -r line
-do
-	option=`echo $line | cut -d : -f 1`
-	value=`echo $line | cut -d : -f 2`
-	export $option=$value
-done < "$1"
+	while getopts ":c:r" opt
+	do
+		case $opt in
+			c)
+				[ -f "$OPTARG" ] && while read -r line
+				do
+					option=`echo $line | cut -d : -f 1`
+					value=`echo $line | cut -d : -f 2`
+					export $option="$value"
+				done < "$OPTARG"
+			;;
+			r)
+				REBUILD=true
+			;;
+			?)
+				echo "Invalid option: -$OPTARG" >&2
+			;;
+		esac
+	done
 
-jail_dir="/usr/share/jail/$jail_name"
+	jail_dir="/usr/share/jail/$jail_name"
 
-build_jail() {
+	[ -d $jail_dir ] && [ $REBUILD == false ] && exit 1
+
 	mkdir -p $jail_dir
 	for command_name in $copy_commands
 	do
@@ -37,5 +52,14 @@ build_jail() {
 	cat $build_script | chroot $jail_dir > /dev/null 2> /dev/null
 }
 
-[ ! -d $jail_dir ] && build_jail
-chroot $jail_dir
+enter() {
+	jail_name="default"
+	[ "$1" != "" ] && jail_name="$1"
+	chroot /usr/share/jail/$jail_name
+}
+
+list() {
+	ls /usr/share/jail | cat
+}
+
+[ "$1" == "list" ] || [ "$1" == "enter" ] || [ "$1" == "build" ] && "$@"
